[versions]

pws = "1.2.2"

kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"

hilt = "2.57.2"

android-application = "8.13.1"
android-material = "1.13.0"
navigation = "2.9.6"

room = "2.8.4"

kotlinx-datetime = "0.7.1"

kotest = "5.9.1"
kotest-runner-android = "1.1.1"
kotest-extensions-android = "0.1.5"
kotest-multiplatform = "5.9.1"
kotest-framework-datatest = "5.9.1"

robolectric = "4.16"


kaml = "0.97.0"
navigation-fragment-ktx = "2.9.6"
navigation-ui-ktx = "2.9.6"

[libraries]

# PWS Libraries
pws-domain = { module = "io.github.alelk.pws.domain:domain", version.ref = "pws" }
pws-dbRoom = { module = "io.github.alelk.pws.data:db-room", version.ref = "pws" }
pws-dbRoomTestFixtures = { module = "io.github.alelk.pws.data:db-room-test-fixtures", version.ref = "pws" }
pws-repoRoom = { module = "io.github.alelk.pws.data:repo-room", version.ref = "pws" }
pws-backup = { module = "io.github.alelk.pws.backup:backup", version.ref = "pws" }

# Android
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }

# Kotlin Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

# Date Time
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Database
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" } # https://mvnrepository.com/artifact/androidx.room/room-runtime

# Logging
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

# DI
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" } # https://mvnrepository.com/artifact/com.google.dagger/hilt-android
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" } # https://mvnrepository.com/artifact/com.google.dagger/hilt-compiler

# Preferences
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version = "1.1.7" } # https://mvnrepository.com/artifact/androidx.datastore/datastore-preferences

preference-ktx = { group = "androidx.preference", name = "preference-ktx", version = "1.2.1" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.9.4" }
material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
ambilwarna = { group = "com.github.yukuku", name = "ambilwarna", version = "2.0.1" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version = "3.0.0" }

# Navigation
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" } # https://mvnrepository.com/artifact/androidx.navigation/navigation-fragment
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" } # https://mvnrepository.com/artifact/androidx.navigation/navigation-ui
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx" }

# Test
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest-framework-datatest" } # https://search.maven.org/artifact/io.kotest/kotest-framework-datatest
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" } # https://search.maven.org/artifact/io.kotest/kotest-assertions-core
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" } # https://search.maven.org/artifact/io.kotest/kotest-property
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

androidx-test-core = { group = "androidx.test", name = "core", version = "1.7.0" } # https://mvnrepository.com/artifact/androidx.test/core
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" } # https://mvnrepository.com/artifact/org.robolectric/robolectric
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
kotest-runner-android = { group = "br.com.colman", name = "kotest-runner-android", version.ref = "kotest-runner-android" }
kotest-extensions-android = { group = "br.com.colman", name = "kotest-extensions-android", version.ref = "kotest-extensions-android" } # https://search.maven.org/artifact/br.com.colman/kotest-extensions-android

[plugins]

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android-application" } # https://mvnrepository.com/artifact/com.android.tools.build/gradle
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest-multiplatform" } # https://plugins.gradle.org/plugin/io.kotest.multiplatform
hilt = { id = "com.google.dagger.hilt.android", version = "2.57.2" } # https://mvnrepository.com/artifact/com.google.dagger.hilt.android/com.google.dagger.hilt.android.gradle.plugin