[versions]

kotlin = "2.0.20"
kotlinx-coroutines = "1.9.0"
ksp = "1.0.24"

android-application = "8.6.1"
android-material = "1.12.0"

room = "2.7.0-alpha10"

kotest = "5.9.1"
kotest-runner-android = "1.1.1"
kotest-extensions-android = "0.1.5"

sqlite-bundled = "2.5.0-alpha10"

[libraries]

# Android
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }

# Kotlin Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

# Database
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" } # https://mvnrepository.com/artifact/androidx.room/room-runtime
room-runtime-jvm = { module = "androidx.room:room-runtime-jvm", version.ref = "room" } # https://mvnrepository.com/artifact/androidx.room/room-runtime-jvm
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" } # https://mvnrepository.com/artifact/androidx.room/room-compiler
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" } # https://mvnrepository.com/artifact/androidx.room/room-ktx
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite-bundled" } # https://mvnrepository.com/artifact/androidx.sqlite/sqlite-bundled

# Logging
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

# Preferences
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version = "1.1.1" } # https://mvnrepository.com/artifact/androidx.datastore/datastore-preferences

# Test
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" } # https://search.maven.org/artifact/io.kotest/kotest-assertions-core
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" } # https://search.maven.org/artifact/io.kotest/kotest-property
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
androidx-test-runner = { group = "androidx.test", name = "runner", version = "1.6.2" }
androidx-test-core = { group = "androidx.test", name = "core", version = "1.6.1" }
robolectric = { module = "org.robolectric:robolectric", version = "4.13" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
kotest-runner-android = { group = "br.com.colman", name = "kotest-runner-android", version.ref = "kotest-runner-android" }
kotest-extensions-android = { group = "br.com.colman", name = "kotest-extensions-android", version.ref = "kotest-extensions-android" }

[plugins]

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android-application" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }